### ISSUE TITLE
double quotes cmd "", leads to error

### ISSUE THREAD

**Issue by jpceia** [falmeida42/Minishell#60]

**Comment by falmeida42** [comment]
quotes when removed generate a NULL string. With this code, quotes are replaced by space 

if (!ft_strcmp(start, "\'") || !ft_strcmp(start, ""))
		return (token_new(TOKEN_DQUOTED, ft_strdup(" ")));
if (!ft_strcmp(start, "\"\"") || !ft_strcmp(start, "\""))
		return (token_new(TOKEN_DQUOTED, ft_strdup(" ")));
